### ISSUE TITLE
App Crash when making a request to the database

### ISSUE THREAD

**Issue by giregk** [convertigo/C8oSDKiOS#2]
![image](https://user-images.githubusercontent.com/20740580/42230218-ae4acc0c-7ee8-11e8-81b7-f9076b367be8.png)

I don't know exactly what's causing the bug, but it happens when a request is made to the database.
The login, reset, and sync requests work though.

**Comment by CharlesGrimont** [comment]
Cannot reproduce from a sample ... 

which kind of request are you doing ?
